package io.violabs.picard.v2.resources.service.endpointslice

import io.violabs.konstellation.metaDsl.annotation.DefaultValue
import io.violabs.konstellation.metaDsl.annotation.GeneratedDsl
import io.violabs.picard.common.AppConstants
import io.violabs.picard.domain.k8sResources.APIVersion
import io.violabs.picard.domain.k8sResources.KAPIVersion
import io.violabs.picard.domain.manifest.ServiceResource
import io.violabs.picard.v2.common.ObjectMeta

/**
 * https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/
 *
 * EndpointSlice represents a set of service endpoints.
 * 
 * EndpointSlice represents a set of service endpoints. Most EndpointSlices are created by the 
 * EndpointSlice controller to represent the Pods selected by Service objects. For a given service 
 * there may be multiple EndpointSlice objects which must be joined to produce the full set of 
 * endpoints; you can find all of the slices for a given service by listing EndpointSlices in the 
 * service's namespace whose kubernetes.io/service-name label contains the service's name.
 *
 * apiVersion: discovery.k8s.io/v1
 *
 * import "k8s.io/api/discovery/v1"
 */
@GeneratedDsl(withListGroup = true)
data class EndpointSliceV2(
    @DefaultValue(
        "KAPIVersion.DiscoveryV1",
        AppConstants.DefaultValue.KAPI_VERSION_PACKAGE,
        AppConstants.DefaultValue.KAPI_VERSION_CLASS
    )
    override val apiVersion: Version = KAPIVersion.DiscoveryV1,
    /**
     * Standard object's metadata.
     */
    override val metadata: ObjectMeta? = null,
    /**
     * addressType specifies the type of address carried by this EndpointSlice. All addresses in 
     * this slice must be the same type. This field is immutable after creation. The following 
     * address types are currently supported:
     * * IPv4: Represents an IPv4 Address.
     * * IPv6: Represents an IPv6 Address. 
     * * FQDN: Represents a Fully Qualified Domain Name.
     * 
     * (Deprecated) The EndpointSlice controller only generates, and kube-proxy only processes, 
     * slices of addressType "IPv4" and "IPv6". No semantics are defined for the "FQDN" type.
     */
    val addressType: String,
    /**
     * endpoints is a list of unique endpoints in this slice. Each slice may include a maximum of 
     * 1000 endpoints.
     */
    val endpoints: List<Endpoint>,
    /**
     * ports specifies the list of network ports exposed by each endpoint in this slice. Each port 
     * must have a unique name. Each slice may include a maximum of 100 ports. Services always have 
     * at least 1 port, so EndpointSlices generated by the EndpointSlice controller will likewise 
     * always have at least 1 port. EndpointSlices used for other purposes may have an empty ports list.
     */
    val ports: List<EndpointPort>? = null
) : ServiceResource<EndpointSliceV2.Version, ObjectMeta> {
    interface Version : APIVersion
}